### ISSUE TITLE
Nodes/Herbs (objects) don't show tooltips

### ISSUE THREAD

**Issue by kmrnk** [Evolvee/EvolvePWPUI#50]

**Comment by Evolvee** [comment]
because I disabled it on default,
this UI is not designed for PVE/leveling, its purely for PVP.

However you can remove this by going into TextureScript.lua and delete these lines:

--Blacklist of frames where tooltips mouseovering is hidden(editable)

local tooltipOwnerBlacklist = {
   "ActionButton%d+$",            -- bar buttons
   "MultiBarBottomLeftButton",
   "MultiBarBottomRightButton",
   "MultiBarLeftButton",
   "MultiBarRightButton",
   "MinimapZoneTextButton",
   "MicroButton$",                -- micro buttons
   "^KeyRingButton$",             -- key ring
   "^CharacterBag%dSlot$",        -- bags
   "^MainMenuBarBackpackButton$", -- backpack
}

local GameTooltip_OnShow = GameTooltip:GetScript("OnShow")
GameTooltip:SetScript("OnShow", function(...)
   local owner = this:GetOwner() and this:GetOwner():GetName()
   if owner then
      -- hide world object tooltips like torches and signs
      if owner == "UIParent" and not this:GetUnit() then
         this:Hide()
         return
      end
      -- hide tooltips owned by frames in the blacklist
      for i=1,#tooltipOwnerBlacklist do
         if owner:find(tooltipOwnerBlacklist[i]) then
            this:Hide()
            return
         end
      end
   end
   if GameTooltip_OnShow then
      GameTooltip_OnShow(...)
   end
end)

**Comment by Evolvee** [comment]
Or you can just delete things from the blacklist table and keep the rest

currently only player tooltips are enabled

the code in my ui is not hashed or connected to each other for easy user-customization so u can easily delete whole scripts(their begining and end is marked with "--")
