### ISSUE TITLE
Nameplates mis-alignment

### ISSUE THREAD

**Issue by vamman311** [Evolvee/EvolvePWPUI#57]
Nameplates are not aligned to bars correctly...I've tried quite a few things with the exception of lurning lua....

 I tried editing the art itself by flipping the image along with thickening and widening the image and still have this result.  I want to change the anchor I suppose so that the bars sit flush with the texture.  If not is there a way to disable them entirely.  I looked at the lua in texturescript.lua but am unable to pinpoint the issue.  Help!

![nameplates issue](https://user-images.githubusercontent.com/24787921/38642024-bf3ea016-3da6-11e8-8ee0-e667d895c05d.png)

**Comment by Evolvee** [comment]
It works correctly for me 

![image](https://user-images.githubusercontent.com/1942409/38642730-3a56a06c-3ddb-11e8-9c9d-3f3b365f32ac.png)


I noticed u also dont have the green HP bar texture, are u sure u placed all Interface folders inside the Interface folder? 

I dont know where your problem is but i tried to download the UI and fully unpack it to stock client, copy SavedVariables and it worked just fine...


Try to disable all other addons except TextureScript and Focus Frame.

--

Btw I also noticed you have the level number on the other side of nameplates.. there must be some of your addon causing the issue, not my UI.

**Comment by vamman311** [comment]
Evolvee thank you for the fast response.  You are right, there must have been some add-on interference as a clean install and some color changes fixed it. 

Thanks this is looking better than modui :). (Currently running on Felymyst)

I am still curious what part of the texturescript.lua I can change to anchor nameplates and levels at different heights etc?

**Comment by Evolvee** [comment]
There isnt anything inside TextureScript.lua that affects nameplates yet to my knowledge. Its classic blizzard UI with different colours...

Its probably easy to switch but you would need new art for it as the current .blp texture is "hardcoded"
